### ISSUE TITLE
Support Gitlab for OAuth

### ISSUE THREAD

**Issue by lyda** [nsheridan/cashier#44]
OK, I have a version that works. So now I have some questions.

First, I have an addition to the vendor branch. Would it make things easier to review if I start with a single PR to add the [gitlab api](https://github.com/xanzy/go-gitlab) to it?

Next, design! For gitlab these are the provider options I've made:

Provider|Option|Notes
--|--|--
Gitlab| baseurl | Optional. API url. Default: `https://gitlab.com/api/v3/`
Gitlab| authurl | Optional. Auth url. Default: `https://gitlab.com/oauth/authorize`
Gitlab| tokenurl | Optional. Token url. Default: `https://gitlab.com/oauth/token`
Gitlab| allusers | Allow all valid users to get signed keys.
Gitlab| group | If `allusers` and this are unset then you must whitelist individual users using `users_whitelist`. Otherwise the user must be a member of this group.

So one thing I could do is condense the `*url` options into a single one (`baseurl`) onto which `api/v3/`, `oauth/authorize` and `oauth/token` are appended. You can deploy it such that the url is like `https://some.host/some/prefix/` but other than changing from the root to a sub dir I don't think we need to be able to split it up that much.

It won't match the gitlab api's definition of `baseurl` though in case that might confuse people. Maybe `siteurl`? It would default to `https://gitlab.com/`.

Next design issue is `group`. It might be nice if that was `groups`. So instead of allowing users in the `"wheel"` group I could allow users from the `[ "wheel", "wing" ]` groups. However `Config.Auth.ProviderOpts` is a `map[string]string`. Maybe we could have a `ProviderLists` as `map[string][]string` (assuming I have that definition right)? BTW the group has to be looked up on the path name of the group - anyone can use "wheel" as a name, but only one group can use "wheel" as their path.

Lastly how much foot-protection should we offer? Having `gitlab.com` as the auth provider should exclude `allusers`. If you set `allusers` and then set `group(s)` or `users_whitelist` you're confused, so cashierd should refuse to start till you're not confused. Or no?

**Comment by lyda** [comment]
OK, wrote the above last night and giving it thought the `siteurl` thing is kinds obvious. So did that which nukes code, allows a bit of sanity checking and makes configuration easier. (duh)

So the table above becomes:

Provider|Option|Notes
--|--|--
Gitlab| siteeurl | Optional. The url of the Gitlab site. Default: `https://gitlab.com/`
Gitlab| allusers | Allow all valid users to get signed keys.
Gitlab| group | If `allusers` and this are unset then you must whitelist individual users using `users_whitelist`. Otherwise the user must be a member of this group.

OK, one last issue is that within a group you can have different access levels: Guest, Reporter, Developer, Master and Owner access. Allowing people to specify a minimum level of access required might help. You might allow developers `Developer` access to an `infra` group, but not want them ssh'ing into production for example.

As an aside I've been pushing a dirty change set to [my gitlab](https://github.com/lyda/cashier/tree/gitlab) branch in case you want to see the code. Still needs clean up and I'll make a new branch with a single clean commit for the PR(s).

**Comment by nsheridan** [comment]
Don't worry about adding to the vendor branch. I think tests will fail if vendored files are missing - just include it in the PR.
I don't really mind how complex the provider options gets - I made it a map so that it could be completely arbitrary. 3 options are better than 5 though.

The group question is interesting - GitHub also has groups, and potentially one could also do the same thing with Google auth. It does add some complexity though, given that there's effectively two types of Github/Gitlab provider: the self-hosted and the public kind. At present Cashier's GitHub provider exclusively uses the public Github provider - see endpoints [here](https://github.com/golang/oauth2/blob/master/github/github.go#L13), and authorizes users based either on a whitelist or on organization membership. 
I wonder if it makes sense to split this into 2 providers - `github` and `github-enterprise` (where 'enterprise' == 'self-hosted') and do something similar for gitlab? The `-enterprise` provider could auth all members by default with additional controls around groups, maybe.
This is just off the top of my head thinking (and I'm not trying to burden you with anything here) - I've never used Gitlab in anger or the enterprise editions of either of them. What's your opinion?

**Comment by lyda** [comment]
Gitlab is widely used in a self-hosted way so I think it's more common. I'd be inclined to extend the existing github auth to support enterprise github. Plus I think people could plug a lot of auth sources into this (your plugin future awaits you) and it seems like doing things to expand them further would be unwise.

For both leave the defaults to point at the public sites but then have the `siteurl` point at your local instance.

Having an `allusers` option available for non-default sites would make sense across both as well. In fact it would make sense for GAFYDs too. An alternative to the `allusers` option could be a `users_whitelist = [ "*" ]` or maybe `users_whitelist = [ ":ALL" ]` which could leave room for future extra-user sequences since a principal can never have a colon. In fact gitlab groups and github organisations could go in there: `users_whitelist = [ ":wheel", ":wing" ]`

Or is that too magic?

**Comment by lyda** [comment]
Oh, note that I went with usernames in gitlab because you can have multiple addresses and there's no real "primary" one.

**Comment by lyda** [comment]
Sorry, I had forgotten to do a few bits so I closed PR #46 and opened #47 which also has expanded tests.

**Comment by lyda** [comment]
This is fixed now.
